export const aviatorProducts = [
  [
    {
      name: 'Конфеты Утренняя звезда',
      description: 'это шоколадные конфеты с комбинированной начинкой',
      image: require('../assets/product_1.png'),
      price: 60,
      count: 1,
    },
    {
      name: 'Конфеты Choco Cream',
      description: 'Бисквит-шоколад – это глазированные конфеты',
      image: require('../assets/product_2.png'),
      price: 35,
      count: 1,
    },
    {
      name: 'Конфеты Ла крема',
      description:
        'Бисквит-шоколад – это шоколадные конфеты с кремовой начинкой',
      image: require('../assets/product_3.png'),
      price: 35,
      count: 1,
    },
    {
      name: 'Конфеты Кураж',
      description: 'Бисквит-шоколад – это глазированные шоколадом конфеты',
      image: require('../assets/product_4.png'),
      price: 25,
      count: 1,
    },
  ],
  [
    {
      name: 'Торт «эустома»',
      description: 'сочный шоколадный бисквит',
      image: require('../assets/product_5.png'),
      price: 65,
      count: 1,
    },
    {
      name: 'Торт «розы»',
      description: 'шоколадная карамель с миндалем',
      image: require('../assets/product_6.png'),
      price: 45,
      count: 1,
    },
    {
      name: 'Торт «супер шоколад»',
      description: 'прослойка клубничного пюре и лимонная пропитка',
      image: require('../assets/product_7.png'),
      price: 75,
      count: 1,
    },
    {
      name: 'Торт золотой шар',
      description: 'пряный бисквит на молоке с добавлением кусочков груши',
      image: require('../assets/product_8.png'),
      price: 90,
      count: 1,
    },
  ],
  [
    {
      name: 'Фруктовый Взрыв',
      description: 'сочные тропические фрукты',
      image: require('../assets/product_1.png'),
      price: 5,
      count: 1,
    },
    {
      name: 'Карамельные Забавы',
      description: 'сладкая, маслянистая карамель',
      image: require('../assets/product_1.png'),
      price: 15,
      count: 1,
    },
    {
      name: 'Цитрусовый Рай',
      description: 'яркий, кисло-сладкий цитрус',
      image: require('../assets/product_1.png'),
      price: 5,
      count: 1,
    },
    {
      name: 'Арбуз',
      description: 'освежающая, прохладная мята',
      image: require('../assets/product_1.png'),
      price: 20,
      count: 1,
    },
  ],
];

export const aviatorAllProducts = [
  {
    name: 'Конфеты Утренняя звезда',
    description: 'это шоколадные конфеты с комбинированной начинкой',
    image: require('../assets/product_1.png'),
    price: 60,
    count: 1,
  },
  {
    name: 'Конфеты Choco Cream',
    description: 'Бисквит-шоколад – это глазированные конфеты',
    image: require('../assets/product_2.png'),
    price: 35,
    count: 1,
  },
  {
    name: 'Конфеты Ла крема',
    description: 'Бисквит-шоколад – это шоколадные конфеты с кремовой начинкой',
    image: require('../assets/product_3.png'),
    price: 35,
    count: 1,
  },
  {
    name: 'Конфеты Кураж',
    description: 'Бисквит-шоколад – это глазированные шоколадом конфеты',
    image: require('../assets/product_4.png'),
    price: 25,
    count: 1,
  },
  {
    name: 'Торт «эустома»',
    description: 'сочный шоколадный бисквит',
    image: require('../assets/product_5.png'),
    price: 65,
    count: 1,
  },
  {
    name: 'Торт «розы»',
    description: 'шоколадная карамель с миндалем',
    image: require('../assets/product_6.png'),
    price: 45,
    count: 1,
  },
  {
    name: 'Торт «супер шоколад»',
    description: 'прослойка клубничного пюре и лимонная пропитка',
    image: require('../assets/product_7.png'),
    price: 75,
    count: 1,
  },
  {
    name: 'Торт золотой шар',
    description: 'пряный бисквит на молоке с добавлением кусочков груши',
    image: require('../assets/product_8.png'),
    price: 90,
    count: 1,
  },
  {
    name: 'Фруктовый Взрыв',
    description: 'сочные тропические фрукты',
    image: require('../assets/product_1.png'),
    price: 5,
    count: 1,
  },
  {
    name: 'Карамельные Забавы',
    description: 'сладкая, маслянистая карамель',
    image: require('../assets/product_1.png'),
    price: 15,
    count: 1,
  },
  {
    name: 'Цитрусовый Рай',
    description: 'яркий, кисло-сладкий цитрус',
    image: require('../assets/product_1.png'),
    price: 5,
    count: 1,
  },
  {
    name: 'Арбуз',
    description: 'освежающая, прохладная мята',
    image: require('../assets/product_1.png'),
    price: 20,
    count: 1,
  },
];
